name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  azure_login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login to Azure
        run: |
          az login --service-principal \
                   --username "$(echo $AZURE_CREDENTIALS | jq -r .clientId)" \
                   --password "$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)" \
                   --tenant "$(echo $AZURE_CREDENTIALS | jq -r .tenantId)"

      - name: Verify Azure Login
        run: az account show
